services:
  - type: web
    name: teacher-chatbot
    env: node
    buildCommand: |
      apt-get update -y && 
      apt-get install -y build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev &&
      npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: CORS_ORIGIN
        value: https://midnightblue-rabbit-284995.hostingersite.com
      - key: DB_HOST
        value: srv1156.hstgr.io
      - key: DB_USER
        value: u640211876_chatbot
      - key: DB_NAME
        value: u640211876_chatbot
      - key: DB_PORT
        value: 3306
      - key: MAX_TOKENS
        value: 4096
      - key: TEMPERATURE
        value: 0.7
      - key: MAX_FILE_SIZE
        value: 209715200
      - key: CHUNK_SIZE
        value: 2000
      - key: REQUIRED_API_KEY
        value: d657a91c9708a863991e0eaf95a5c718
      - key: CLAUDE_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: OPENAI_MODEL
        value: gpt-3.5-turbo-16k
      - key: MODEL
        value: claude-3-sonnet-20240229
    healthCheckPath: /api/health
    autoDeploy: true
    disk:
      name: training-docs
      mountPath: /opt/render/project/src/training-docs
      sizeGB: 1
